let translationalLanguage = [];
translationalLanguage['Spanish'] = {
  Privacy_Policy:'política de privacidad',
  privacy_policy: 'política de privacidad',
  Next: 'Próxima',
  onboarding: 'inducción',
  GPSTracker: 'Rastreador de GPS',
  GPSTracker_real_time_location:
    'Rastreador GPS ubicación en tiempo real precio seguro y confiable Calcule la distancia entre dos puntos y navegue por ellos',
  skip: 'saltar',
  station_Alert: 'alerta de estación',
  Noftify_you:
    'Notificarte cuando un miembro de tu círculo llega o sale de una casa o lugar de trabajo.',
  Number_Tracker: 'Rastreadora de números',
  Got_Number_Details:
    'Obtuve detalles del número e identifique la ejecución del número deseado',
  Location: 'Ubicación',
  Allow_permission: 'Permitir permiso',
  Contact: 'Contacto',
  Share_Location: 'Comparte ubicacion',
  Whatsapp: 'Whatsapp',
  Facebook: 'Facebook',
  Instagram: 'Instagram',
  FindAddress: 'Encuentra la dirección',
  GPS_Coordinate: 'Coordenadas GPS',
  Home: 'Hogar',
  speedometer: 'velocímetro',
  search_Number: 'número de búsqueda',
  GPS_Tool: 'GPS herramienta',
  start: 'comenzar',
  Add_New_location: 'Agregar nueva ubicación',
  Move_inside: 'Mover dentro',
  Move_outside: 'Mover fuera',
  Add_place: 'Añadir lugar',
  selectcountrycode: 'Seleccione el código de país',
  enterphonenumber: 'Ingresa número telefónico',
  you_have_not_added_location: 'no tienes ninguna ubicación agregada',
  averge_speed: 'la velocidad promedio',
  max_speed: 'máxima velocidad',
  click_here_to_add_new_location:
    'Haga clic aquí para agregar una nueva ubicación',
  areacode: 'Codigo de AREA',
  compass: 'Brújula',
  altitudemeter: 'Medidor de altitud',
  worldclock: 'Reloj mundial',
  ipaddress: 'Dirección IP',
  search:'Buscar'
};
translationalLanguage['English'] = {
  Privacy_Policy:'Privacy Policy',
  privacy_policy: 'I read and Accept Privacy Policy',
  Next: 'Next',
  onboarding: 'Onboarding',
  GPSTracker: 'GPSTracker',
  GPSTracker_real_time_location:
    'GPS tracker real time location precise safe and Reliable Calculate the distance between two points and navigate them',
  skip: 'skip',
  station_Alert: 'Station Alert',
  Noftify_you:
    'Notify you when a member of your circle arrives or leaves a home or place of bussiness',
  Number_Tracker: 'Number Traker',
  Got_Number_Details:
    'Got Number details and identify the execution of desired number',
  Location: 'Location',
  Allow_permission: 'Allow Permission',
  Contact: 'Contact',
  Share_Location: 'Share Location',
  Whatsapp: 'Whatsapp',
  Facebook: 'Facebook',
  Instagram: 'Instagram',
  FindAddress: 'Find Address',
  GPS_Coordinate: 'GPS Coordinate',
  Home: 'Home',
  speedometer: 'Speedo Meter',
  search_Number: 'Search Number',
  GPS_Tool: 'GPS Tool',
  start: 'Start',
  Add_New_location: 'Add New Location',
  Move_inside: 'Moving inside',
  Move_outside: 'Moving Outside',
  Add_place: 'Add Place',
  selectcountrycode: 'Select Country Code',
  enterphonenumber: 'Enter Phone Number',
  you_have_not_added_location: 'you have no added location',
  click_here_to_add_new_location: 'Click here to add new location',
  areacode: 'Area Code',
  compass: 'Compass',
  altitudemeter: 'Altitude Meter',
  worldclock: 'World Clock',
  ipaddress: 'IP Address',
  averge_speed: 'Avg speed',
  max_speed: 'max speed',
  search:'Search'
};
(translationalLanguage['Urdu'] = {
  Privacy_Policy:'رازداری کی پالیسی',
  privacy_policy: 'میں پرائیویسی پالیسی پڑھتا ہوں اور قبول کرتا ہوں۔',
  Next: 'اگلے',
  onboarding: 'آن بورڈنگ',
  GPSTracker: 'جی پی ایس ٹریکر',
  GPSTracker_real_time_location:
    'GPS ٹریکر ریئل ٹائم لوکیشن کی قیمت محفوظ اور قابل اعتماد دو پوائنٹس کے درمیان فاصلے کا حساب لگائیں اور انہیں نیویگیٹ کریں',
  skip: 'چھوڑ دو',
  station_Alert: 'اسٹیشن الرٹ',
  Noftify_you:
    'جب آپ کے حلقے کا کوئی رکن گھر یا کاروبار کی جگہ آئے یا چھوڑے تو آپ کو مطلع کریں',
  Number_Tracker: 'نمبر ٹریکر',
  Got_Number_Details:
    'نمبر کی تفصیلات حاصل کریں اور مطلوبہ نمبر کے نفاذ کی شناخت کریں',
  Location: 'مقام',
  Allow_permission: 'اجازت دیں۔',
  Contact: 'رابطہ کریں۔',
  Share_Location: 'مقام کا اشتراک کریں۔',
  Whatsapp: 'واٹس ایپ',
  Facebook: 'فیس بک',
  Instagram: 'انسٹاگرام',
  FindAddress: 'پتہ تلاش کریں۔',
  GPS_Coordinate: 'GPS کوآرڈینیٹ',
  Home: 'گھر',
  speedometer: 'سپیڈومیٹر',
  search_Number: 'نمبر تلاش کریں۔',
  GPS_Tool: 'جی پی ایس ٹول',
  start: 'شروع',
  Add_New_location: 'نیا مقام شامل کریں',
  Move_inside: 'اندر چلو',
  Move_outside: 'باہر منتقل کریں۔',
  Add_place: 'جگہ شامل کریں۔',
  selectcountrycode: 'ملک کا کوڈ منتخب کریں۔',
  enterphonenumber: 'فون نمبر درج کریں۔',
  you_have_not_added_location: 'آپ کے_ہے_نہیں_شامل_مقام',
  click_here_to_add_new_location: 'نیا مقام شامل کرنے کے لیے یہاں کلک کریں۔',
  areacode: 'علاقے کا کوڈ',
  compass: 'کمپاس',
  altitudemeter: 'اونچائی میٹر',
  worldclock: 'عالمی گھڑی',
  ipaddress: 'IP پتہ',
  averge_speed: 'اوسط رفتار',
  max_speed: 'رفتار کی آخری حد',
  search:'تلاش کریں۔'
}),
  (translationalLanguage['Portuguese'] = {
    Privacy_Policy:'política de Privacidade',
    privacy_policy: 'Li e aceito a Política de Privacidade',
    Next: 'Próxima',
    onboarding: 'integração',
    GPSTracker: 'Rastreador GPS',
    GPSTracker_real_time_location:
      'Rastreador GPS, localização em tempo real, preço seguro e confiável Calcule a distância entre dois pontos e navegue por eles',
    skip: 'pular',
    station_Alert: 'alerta de estação',
    Noftify_you:
      'Notificá-lo quando um membro do seu círculo chegar ou sair de uma casa ou local de trabalho',
    Number_Tracker: 'Rastreador de números',
    Got_Number_Details:
      'Obtenha detalhes do número e identifique a execução do número desejado',
    Location: 'Localização',
    Allow_permission: 'Permitir permissão',
    Contact: 'Contato',
    Share_Location: 'Compartilhar localização',
    Whatsapp: 'Whatsapp',
    Facebook: 'Facebook',
    Instagram: 'Instagram',
    FindAddress: 'Encontrar endereço',
    GPS_Coordinate: 'Coordenada GPS',
    Home: 'Lar',
    speedometer: 'velocímetro',
    search_Number: 'número de pesquisa',
    GPS_Tool: 'Ferramenta GPS',
    start: 'começar',
    Add_New_location: 'Adicionar novo local',
    Move_inside: 'Mover_dentro',
    Move_outside: 'Mover_para fora',
    Add_place: 'Adicionar lugar',
    selectcountrycode: 'Selecione o código do país',
    enterphonenumber: 'Digite o número de telefone',
    you_have_not_added_location: 'você não tem nenhum local adicionado',
    click_here_to_add_new_location: 'Clique aqui para adicionar novo local',
    areacode: 'Código de área',
    compass: 'Bússola',
    altitudemeter: 'Medidor de altitude',
    worldclock: 'Relógio mundial',
    ipaddress: 'Endereço de IP',
    averge_speed: 'AVG velocidade',
    max_speed: 'velocidade máxima',
    search:'Procurar'
  }),
  (translationalLanguage['Hindi'] = {
    Privacy_Policy:'गोपनीयता नीति',
    privacy_policy: 'मैं गोपनीयता नीति पढ़ता हूं और स्वीकार करता हूं',
    Next: 'अगला',
    onboarding: 'ज्ञानप्राप्ति',
    GPSTracker: 'जीपीएस ट्रैकर',
    GPSTracker_real_time_location:
      'जीपीएस ट्रैकर वास्तविक समय स्थान कीमत सुरक्षित और विश्वसनीय दो बिंदुओं के बीच की दूरी की गणना करें और उन्हें नेविगेट करें',
    skip: 'छोडना',
    station_Alert: 'स्टेशन अलर्ट',
    Noftify_you:
      'जब आपके सर्कल का कोई सदस्य घर या व्यवसाय स्थल पर आता है या निकलता है तो आपको सूचित करें',
    Number_Tracker: 'नंबर ट्रैकर',
    Got_Number_Details:
      'संख्या विवरण प्राप्त करें और वांछित संख्या के निष्पादन की पहचान करें',
    Location: 'जगह',
    Allow_permission: 'अनुमति दें',
    Contact: 'संपर्क',
    Share_Location: 'स्थान साझा करें',
    Whatsapp: 'Whatsapp',
    Facebook: 'Facebook',
    Instagram: 'Instagram',
    FindAddress: 'पता ढूंढ़ो',
    GPS_Coordinate: 'जीपीएस समन्वय',
    Home: 'घर',
    speedometer: 'स्पीडोमीटर',
    search_Number: 'खोज संख्या',
    GPS_Tool: 'जीपीएस उपकरण',
    start: 'शुरू',
    Add_New_location: 'नया स्थान जोड़ें',
    Move_inside: 'अंदर चल रहा है',
    Move_outside: 'बाहर घूमना',
    Add_place: 'स्थान जोड़ें',
    selectcountrycode: 'देश कोड चुनें',
    enterphonenumber: 'फोन नंबर दर्ज',
    you_have_not_added_location: 'आपके पास कोई अतिरिक्त स्थान नहीं है',
    click_here_to_add_new_location: 'नया स्थान जोड़ने के लिए यहां क्लिक करें',
    areacode: 'एरिया कोड',
    compass: 'दिशा सूचक यंत्र',
    altitudemeter: 'ऊंचाई मीटर',
    worldclock: 'वर्ल्ड क्लॉक',
    ipaddress: 'आईपी ​​पता',
    averge_speed: 'औसत गति',
    max_speed: 'अधिकतम चाल',
    search:'खोज'
  });
  translationalLanguage['French'] = {
    Privacy_Policy:'politique de confidentialité',
    privacy_policy: 'politique de confidentialité',
    Next: 'Suivante',
    onboarding: 'Intégration',
    GPSTracker: 'Traceur GPS',
    GPSTracker_real_time_location:
      'Traceur GPS, localisation en temps réel, prix sûr et fiable, calculez la distance entre deux points et parcourez-les',
    skip: 'sauter',
    station_Alert: 'Alerte de station',
    Noftify_you:
      'Vous avertir lorsqu un membre de votre cercle arrive ou quitte un domicile ou un lieu de travail',
    Number_Tracker: 'Suivi des numéros',
    Got_Number_Details:
      'Obtenez les détails du numéro et identifiezl exécution du numéro souhaité',
    Location: 'Emplacement',
    Allow_permission: `Autoriser l'autorisation`,
    Contact: 'Contact',
    Share_Location: 'Emplacement partagé',
    Whatsapp: 'Whatsapp',
    Facebook: 'Facebook',
    Instagram: 'Instagram',
    FindAddress: 'Trouver une adresse',
    GPS_Coordinate: 'Coordonnées GPS',
    Home: 'Maison',
    speedometer: 'Compteur de vitesse',
    search_Number: 'Numéro de recherche',
    GPS_Tool: 'Outil GPS',
    start: 'Commencer',
    Add_New_location: 'Ajouter un nouvel emplacement',
    Move_inside: `Se déplacer à l'intérieur`,
    Move_outside: `Déménager à l'extérieur`,
    Add_place: 'Ajouter un lieu',
    selectcountrycode: 'Sélectionnez le code du pays',
    enterphonenumber: 'Entrez le numéro de téléphone',
    you_have_not_added_location: `vous n'avez pas d'emplacement ajouté`,
    click_here_to_add_new_location: 'Cliquez ici pour ajouter un nouvel emplacement',
    areacode: 'Indicatif régional',
    compass: 'Boussole',
    altitudemeter: 'Altimètre',
    worldclock: 'Horloge mondiale',
    ipaddress: 'Adresse IP',
    averge_speed: 'vitesse moyenne',
    max_speed: 'vitesse maximale',
    search:'Recherche'
  };
  translationalLanguage['Japanese'] = {
    Privacy_Policy:'プライバシーポリシー',
    privacy_policy: 'プライバシーポリシーを読んで同意します',
    Next: '次',
    onboarding: 'オンボーディング',
    GPSTracker: 'GPSトラッカー',
    GPSTracker_real_time_location:
      'GPS トラッカー リアルタイム位置正確で安全かつ信頼性の高い 2 点間の距離を計算し、それらをナビゲートします',
    skip: 'スキップ',
    station_Alert: 'ステーションアラート',
    Noftify_you:
      'サークルのメンバーが家や職場に到着または出発したときに通知します',
    Number_Tracker: 'ナンバートラッカー',
    Got_Number_Details:
      '番号の詳細を取得し、希望の番号の実行を特定します',
    Location: 'Location',
    Allow_permission: '許可を許可する',
    Contact: '接触',
    Share_Location: '共有場所',
    Whatsapp: 'ワッツアップ',
    Facebook: 'フェイスブック',
    Instagram: 'インスタグラム',
    FindAddress: '住所の検索',
    GPS_Coordinate: 'GPS 座標',
    Home: '家',
    speedometer: 'スピードメーター',
    search_Number: '検索番号',
    GPS_Tool: 'GPSツール',
    start: 'Start',
    Add_New_location: '始める',
    Move_inside: '内部への移動',
    Move_outside: '屋外への移動',
    Add_place: '場所を追加',
    selectcountrycode: '国コードを選択してください',
    enterphonenumber: '電話番号を入力してください',
    you_have_not_added_location: '追加された場所がありません',
    click_here_to_add_new_location: '新しい場所を追加するにはここをクリックしてください',
    areacode: '市外局番',
    compass: '方位磁針',
    altitudemeter: '高度計',
    worldclock: '世界時計',
    ipaddress: 'IPアドレス',
    averge_speed: '平均速度',
    max_speed: 'マックス・スピード',
    search:'検索'
  };
  translationalLanguage['Korean'] = {
    Privacy_Policy:'개인 정보 정책',
    privacy_policy: '개인정보 보호정책을 읽고 이에 동의합니다.',
    Next: '다음',
    onboarding: '온보딩',
    GPSTracker: 'GPS 추적기',
    GPSTracker_real_time_location:
      'GPS 추적기 실시간 위치는 안전하고 신뢰할 수 있습니다. 두 지점 사이의 거리를 계산하고 탐색합니다.',
    skip: '건너뛰다',
    station_Alert: '스테이션 알림',
    Noftify_you:
      '서클 멤버가 집이나 회사에 도착하거나 떠날 때 알림을 받습니다.',
    Number_Tracker: '번호 추적기',
    Got_Number_Details:
      '번호 세부정보를 받아 원하는 번호의 실행 여부를 확인',
    Location: '위치',
    Allow_permission: '권한 허용',
    Contact: '연락하다',
    Share_Location: '위치 공유',
    Whatsapp: '왓츠앱',
    Facebook: '페이스북',
    Instagram: '인스 타 그램',
    FindAddress: '주소 찾기',
    GPS_Coordinate: 'GPS 좌표',
    Home: '집',
    speedometer: '속도계',
    search_Number: '검색번호',
    GPS_Tool: 'GPS 도구',
    start: '시작',
    Add_New_location: '새 위치 추가',
    Move_inside: '내부로 이동',
    Move_outside: '외부로 이사하기',
    Add_place: '장소 추가',
    selectcountrycode: '국가 코드 선택',
    enterphonenumber: '전화번호 입력',
    you_have_not_added_location: '추가된 위치가 없습니다',
    click_here_to_add_new_location: '새 위치를 추가하려면 여기를 클릭하세요.',
    areacode: '지역 코드',
    compass: '나침반',
    altitudemeter: '고도 측정기',
    worldclock: '세계시계',
    ipaddress: 'IP 주소',
    averge_speed: '평균 속도',
    max_speed: '최대 속도',
    search:'찾다'
  };

export default translationalLanguage;
