
const LOCATION_PERMISSION = 'LOCATION_PERMISSON';
const CONTACT_PERMISSION = 'CONTACT_PERMISSION';
const SET_CONTACT = 'SET_CONTACT';
const SET_LOCATION = 'SET_LOCATION';
const SET_COUNTRIES="SET_CONTRIES"
const SET_HOME = 'SET_HOME';
const ADDRESS_LOCATION = 'ADDRESS_LOCATION';
const ADD_NEW_TRACK = 'ADD_NEW_TRACK';
const DELETE_TRACK = 'DELETE_TRACK';
const ADD_COUNTRIES = 'ADD_COUNTRIES';
const DELETE_COUNTRY = 'DELETE_COUNTRY';
const ADD_LOCATION_ALERT = 'ADD_LOCATION_ALERT';
const DELETE_LOCATION_ALERT = 'DELETE_LOCATION_ALERT';
const ACTIVE_LOCATION_ALERT = 'ACTIVE_LOCATION_ALERT';
const UPDATE_LOCATION_ALERT_ITEM = 'UPDATE_LOCATION_ALERT_ITEM';
const SET_ROUTE_NAME = 'SET_ROUTE_NAME';
const ENTRY_ALERT = 'ENTRY_ALERT';
const EXIT_ALERT = 'EXIT_ALERT';
const UPDATE_ALERT_ITEM_COMPLETE = 'UPDATE_ALERT_ITEM_COMPLETE';
const SET_SHOW_APP_OEPN_AD = 'SET_SHOW_APP_OEPN_AD';
const PURCHASE_ITEM = 'PURCHASE_ITEM';
const RESTORE_ITEM = 'RESTORE_ITEM';
const SELECT_LANGUAGE = "SELECT_LANGUAGE"
const SET_APP_OPEN_STATUS ='SET_APP_OPEN_STATUS';
const STORED_LOCATION = 'STORED_LOCATION';
const ADD_COUNT='ADD_COUNT';
const REMOTE_CONFIG = 'REMOTE_CONFIG';
const USER_CONSENT = "USER_CONSENT";
export {
    LOCATION_PERMISSION,
    CONTACT_PERMISSION,
    SET_CONTACT,
    SET_LOCATION,
    SET_HOME,
    SET_COUNTRIES,
    ADDRESS_LOCATION,
    ADD_NEW_TRACK,
    DELETE_TRACK,
    DELETE_COUNTRY,
    ADD_COUNTRIES,
    ADD_LOCATION_ALERT,
    DELETE_LOCATION_ALERT,
    ACTIVE_LOCATION_ALERT,
    UPDATE_LOCATION_ALERT_ITEM,
    SET_ROUTE_NAME,
    SET_SHOW_APP_OEPN_AD,
    ENTRY_ALERT,
    EXIT_ALERT,
    UPDATE_ALERT_ITEM_COMPLETE,
    RESTORE_ITEM,
    PURCHASE_ITEM,
    SELECT_LANGUAGE,
    SET_APP_OPEN_STATUS,
    STORED_LOCATION,
    ADD_COUNT,
    REMOTE_CONFIG,
    USER_CONSENT
}